Config = {}

Config.trash = {
	{name = "rotten_apple", label = "Manzana podrida", weight = 0.2, type = "item"},
	{name = "yogur", label = "Yogur caducado", weight = 0.2, type = "item"},
	{name = "spoil_meat", label = "Carne podrida", weight = 0.3, type = "item"},
	{name = "potato", label = "Patata pocha", weight = 0.3, type = "item"},
	{name = "rotten_bread", label = "Pan mohoso", weight = 0.3, type = "item"},
	{name = "bombon", label = "Bombon mordido", weight = 0.1, type = "item"},
	{name = "bitten_donut", label = "Donut mordido", weight = 0.2, type = "item"},
	{name = "bitten_cookie", label = "Galleta mordida", weight = 0.1, type = "item"},
	{name = "used_condom", label = "Condon usado", weight = 0.1, type = "item"},
	{name = "diaper", label = "Pañal sucio", weight = 0.3, type = "item"},
	{name = "wet_paper", label = "Papel mojado", weight = 0.1, type = "item"},
	{name = "cleanex", label = "Pañuelo usado", weight = 0.1, type = "item"},
	{name = "old_book", label = "Libro viejo", weight = 0.5, type = "item"},
	{name = "jeringuilla", label = "Jeringuilla", weight = 0.1, type = "item"},
	{name = "used_water", label = "Agua a medias", weight = 0.2, type = "item"},
	{name = "used_razor", label = "Maquinilla usada", weight = 0.2, type = "item"},
	{name = "used_spray", label = "Spray vacio", weight = 0.3, type = "item"},
	{name = "tijeras", label = "Tijeras", weight = 0.4, type = "item"},
	{name = "empty_y", label = "Yogur vacio", weight = 0.1, type = "item"},
	{name = "empty_e", label = "Carton de huevos", weight = 0.1, type = "item"},
	{name = "empty_c", label = "Lata vacia", weight = 0.2, type = "item"},
	{name = "smash_can", label = "Latas aplastadas", weight = 0.4, type = "item"},
	{name = "cigarette_butt", label = "Colillas", weight = 0.1, type = "item"},
	{name = "verdura_pocha", label = "Verduras pochas", weight = 0.3, type = "item"},
	{name = "tea_bag", label = "Bolsita de Te", weight = 0.1, type = "item"},
	{name = "empty_t", label = "Tabaco vacio", weight = 0.1, type = "item"},
	{name = "corcho", label = "Corcho", weight = 0.1, type = "item"},
	{name = "pua", label = "Púa", weight = 0.1, type = "item"}

}

Config.prizeItems = {
	{
		{name = "herradura", label = "Herradura", weight = 0.7, type = "item"},
		{name = "piezas", label = "Piezas sueltas", weight = 0.3, type = "item"},
		{name = "muelle", label = "Muelle", weight = 0.2, type = "item"},
		{name = "toycar", label = "Coche de juguete", weight = 0.3, type = "item"},
		{name = "pipe", label = "Tuberia", weight = 0.7, type = "item"},
		{name = "tpipe", label = "Tuberia en T", weight = 0.3, type = "item"},
		{name = "grifo", label = "Grifo", weight = 0.2, type = "item"},
		{name = "valve", label = "Valvula", weight = 0.5, type = "item"},
		{name = "tornillos", label = "Tornillos", weight = 0.2, type = "item"},
		{name = "wires", label = "Cables", weight = 0.5, type = "item"},
		{name = "usb", label = "USB", weight = 0.1, type = "item"},
		{name = "water", label = "Agua", weight = 0.5, type = "item"},
		{name = "bandage", label = "Bendas", weight = 0.6, type = "item"},
		{name = "chips", label = "Lays", weight = 0.4, type = "item"}
	},
	{
		{name = "carbat", label = "Bateria de coche", weight = 2.1, type = "item"},
		{name = "copperpipe", label = "Tuberia de cobre", weight = 1.5, type = "item"},
		{name = "maneta", label = "Maneta", weight = 0.4, type = "item"},
		{name = "candado", label = "Candado", weight = 0.4, type = "item"},
		{name = "hdd", label = "Disco duro", weight = 0.4, type = "item"},
		{name = "ram", label = "Memoria ram", weight = 0.2, type = "item"},
		{name = "psu", label = "PSU", weight = 0.8, type = "item"},
		{name = "pizza", label = "Pizza", weight = 0.8, type = "item"},
		{name = "sprite", label = "7up", weight = 0.5, type = "item"},
		{name = "bullet_shell", label = "Casquillos .45", weight = 0.2, type = "item"},
		{name = "puar", label = "Púa Firmada", weight = 0.8, type = "item"},
	},
	{
		{name = "steal_phone", label = "Telefono Robado", weight = 0.6, type = "item"},
		{name = "steal_radio", label = "Radio robada", weight = 0.8, type = "item"},
		{name = "filter", label = "Filtro", weight = 0.6, type = "item"},
		{name = "audio_card", label = "T. Audio", weight = 0.3, type = "item"},
		{name = "old_hardware", label = "Hardware viejo", weight = 0.9, type = "item"},
		{name = "monster", label = "Monster", weight = 0.7, type = "item"},
		{name = "taco", label = "Taco mexicano", weight = 0.8, type = "item"},
		{name = "aquarius", label = "Aquarius", weight = 0.5, type = "item"},
		{name = "weed_pooch", label = "Chivato de Maria", weight = 0.6, type = "item", count = 3},
		{name = "radio_trans", label = "Trans. de radio", weight = 1, type = "item"},
		{name = "meds_box", label = "Cajas de Farmacos", weight = 1, type = "item"},
		{name = "correo_ajeno", label = "Correo ajeno", weight = 1, type = "item"},
	},
	{
		{name = "microwave", label = "Microhondas", weight = 3.2, type = "item"},
		{name = "computer_case", label = "Caja pc", weight = 1.4, type = "item"},
		{name = "dvd", label = "Reproductor DVD", weight = 1.3, type = "item"},
		{name = "batidora", label = "Batidora", weight = 0.9, type = "item"},
		{name = "coke_pooch", label = "Pollo de coca", weight = 0.6, type = "item", count = 3},
		{name = "ledgers", label = "Ledger Nano S", weight = 0.1, type = "item"},
		{name = "smg_mag", label = "Cargador SMG", weight = 1.2, type = "item"},
		{name = "mouse", label = "Raton", weight = 0.3, type = "item"},
		{name = "keyboard", label = "Teclado", weight = 0.8, type = "item"},
	},
	{
		{name = "medikit", label = "Botiquín", weight = 1.2, type = "item"},
		{name = "fixkit", label = "Kit de reparación", weight = 2, type = "item"},
		{name = "binoculars", label = "Prismaticos", weight = 1.8, type = "item"},
		{name = "morphine", label = "Morfina", weight = 0.3, type = "item"},
		{name = "gpu", label = "T. Grafica", weight = 0.4, type = "item"},
		{name = "adrenaline_shot", label = "Adrenalina", weight = 0.3, type = "item"},
		{name = "WEAPON_SWITCHBLADE", label = "Navaja", weight = 0, type = "weapon"},
		{name = "WEAPON_MINISMG", label = "Mini SMG", weight = 0, type = "weapon"},
		{name = "meth_pooch", label = "Bolsa de meta", weight = 0.8, type = "item", count = 5},
	}
}