fine_types = 
{
    [1] = {
        {id = 1, label = 'Uso abusivo del claxon',amount = 130},
        {id = 2, label = 'Atravesar una línea continua',amount = 240},
        {id = 3, label = 'Circular en sentido contrario',amount = 800},
	    {id = 4, label = 'Aparcar en zona de minusvalidos',amount = 300},
        {id = 5, label = 'Cambio de sentido no autorizado',amount = 250},
        {id = 6, label = 'Parada no permitida / peligrosa',amount = 150},
        {id = 7, label = 'Estacionamiento indebido',amount = 170},
        {id = 8, label = 'No respetar un Stop',amount = 310},
        {id = 9, label = 'No respetar un semáforo',amount = 330},
        {id = 10, label = 'Adelantamiento peligroso',amount = 300},
        {id = 11, label = 'Vehiculo deteriorado',amount = 150},
        {id = 12, label = 'Conducir sin licencia',amount = 1500},
        {id = 13, label = 'Delito de fuga',amount = 2000},
        {id = 14, label = 'Exceso de velocidad < 5 kmh',amount = 150},
        {id = 15, label = 'Exceso de velocidad 6-15 kmh',amount = 220},
        {id = 16, label = 'Exceso de velocidad 16-30 kmh',amount = 380},
        {id = 17, label = 'Exceso de velocidad > 30 kmh',amount = 600},
    },
    [2] = {
        {id = 18, label = 'Obstrucción de tráfico',amount = 210},
        {id = 19, label = 'Desorden público',amount = 190},
        {id = 20, label = 'Obstrucción a la justicia',amount = 1530},
        {id = 21, label = 'Insulto a / entre civiles',amount = 175},
        {id = 22, label = 'Desprecio a un oficial de policía',amount = 1810},
        {id = 23, label = 'Amenaza verbal o intimidación a un civil',amount = 390},
	    {id = 24, label = 'Amenaza verbal o intimidación a un policía',amount = 2550},
	    {id = 25, label = 'Agresión a un civil',amount = 1000},
        {id = 26, label = 'Agresión a un policía',amount = 3500},
	    {id = 27, label = 'Manifestación ilegal',amount = 450},
        {id = 28, label = 'Intento de Soborno',amount = 1800},
	    {id = 29, label = 'Desacato a la autoridad',amount = 2800},

    },
    [3] = {
        {id = 30, label = 'Posesión de arma blanca en la ciudad',amount = 1250},
        {id = 31, label = 'Posesión de un arma letal en la ciudad',amount = 3500},
        {id = 32, label = 'Portar un arma sin autorización {Falta de licencia}',amount = 6000},
        {id = 33, label = 'Portar un arma ilegal de gran calibre',amount = 2700},
        {id = 34, label = 'Pillado infraganti forzando cerradura',amount = 300},
        {id = 35, label = 'Robo de vehiculo',amount = 1800},
        {id = 36, label = 'Venta de drogas',amount = 2000},
        {id = 37, label = 'Fabricación de droga',amount = 2950},
        {id = 38, label = 'Toma de rehenes civiles',amount = 1500},
	    {id = 39, label = 'Acoso psicológico',amount = 1000},
        {id = 40, label = 'Secuestro de un agente estatal',amount = 3000},
	    {id = 41, label = 'Negar o borrar grabaciones',amount = 2000},
	    {id = 42, label = 'Estafa comercial',amount = 4000},
	    {id = 43, label = 'Robo a particular',amount = 1650},
        {id = 44, label = 'Robo a tienda',amount = 2850},
	    {id = 45, label = 'Robo a ammu-nation',amount = 3800},
	    {id = 46, label = 'Robo a joyería',amount = 5000},
        {id = 47, label = 'Robo a sucursal',amount = 7500},
    },
    [4] = {
        {id = 48, label = 'Disparar a un civil',amount = 2000},
        {id = 49, label = 'Disparar a un agente',amount = 5500},
        {id = 50, label = 'Suplantación de indentidad',amount = 5000},
        {id = 51, label = 'Intento de asesinato a un civil',amount = 3000},
        {id = 52, label = 'Intento e asesinato a un agente',amount = 10000},
        {id = 53, label = 'Asesinato de un civil',amount = 10000},
        {id = 54, label = 'Asesinato de un agente',amount = 50000},
        {id = 55, label = 'Homicidio involuntario',amount = 2800},
        {id = 56, label = 'Trafico de drogas. Investagación',amount = 75000},
        {id = 57, label = 'Robo a Yate',amount = 10000},
        {id = 58, label = 'Robo a los Laboratorios Humane',amount = 30000},
        {id = 59, label = 'Robo al banco central',amount = 100000},
    }
}

